### ISSUE TITLE
Install the plugin in Joomla 2.5.x

### ISSUE THREAD

**Issue by khookeiwai** [GreenCape/extension-export#11]
Hi, currently I install the plugin [extension-export] at my Joomla Site 2.5.x and my site is down. How do I manually uninstall the plugin asap? 

I do expected my site back to normal.

My site is down now.

Joomla 2.5.x

**Comment by nibra** [comment]
Am 18.02.19 um 10:32 schrieb khookeiwai:

> Hi, currently I install the plugin [extension-export] at my Joomla Site 2.5.x and my site is down. How do I manually uninstall the plugin asap? 

Go to the database directly, using eg. PhpMyAdmin. Find the extension in
the "extensions" directory and set "enabled" to "0".

Regards,
Niels
