### ISSUE TITLE
Site Broke, Front and Backend. Error 500.

### ISSUE THREAD

**Issue by pleasantgears1** [GreenCape/extension-export#8]
### Steps to reproduce the issue
Downloaded v1.0.0. Installed and when enable plugin, site broke.

### Actual result
Error 500.

### System information (as much as possible)

PHP Built On | Linux dev1 3.2.0-0.bpo.4-amd64 .1 SMP Debian 3.2.57-3+deb7u2~bpo60+1 x86_64
-- | --
Database Version | 5.1.73-1
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8_general_ci
PHP Version | 5.6.31
Web Server | Apache/2.2.16 (Debian)
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by pleasantgears1** [comment]
Error 500 went away when updated Joomla to 3.8.5

**Comment by nibra** [comment]
Added version requirement (Joomla 3.8+) to the README file.
