### ISSUE TITLE
Database tables not created.

### ISSUE THREAD

**Issue by pleasantgears1** [GreenCape/extension-export#9]
### Steps to reproduce the issue
Was able to export a component to a new site. After installation and upon using the component. I see errors: 
1146 Table 'www_mysite_com.#__storelocator_cats' doesn't exist, 
0 Table 'www_,mysite_com.#__storelocator_marker_types' doesn't exist

### Actual result
Was not able to use the component because of database table errors.

### System information (as much as possible)

PHP Built On | Linux dev1 3.2.0-0.bpo.4-amd64 .1 SMP Debian 3.2.57-3+deb7u2~bpo60+1 x86_64
Database Version | 5.1.73-1
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.7
Web Server | nginx/1.13.3
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by nibra** [comment]
The exporter does only include the SQL files that were originally provided with the extension (if listet in the manifest file). The detection of tables and structure changes as well as data export are subject to [future development](https://github.com/GreenCape/extension-export/issues/7).

## Workaround

Export the relevant tables manually (eg., with PHPMyAdmin) and put it into the component's SQL file instead of the original content.

**Comment by pleasantgears1** [comment]
In the exported zip file, I do see some lines in the xml file that deals with tables. Im not sure why these tables were not created or maybe the names of the table are wrong compare to the table names in the error message.

`<tables>`

`<table>`#__storelocator_locations`</table>`

`<table>`#__storelocator_cats`</table>`

`<table>`#__storelocator_tags`</table>`

`<table>`#__storelocator_tag_map`</table>`

`<table>`#__storelocator_marker_types`</table>`

`<table>`#__storelocator_log_search`</table>`

`</tables>`

**Comment by pleasantgears1** [comment]
Can I use ftp to copy the sql folder from one site to another without using phpMyAdmin?

**Comment by nibra** [comment]
That's a strange (i.e., not Joomla standard) XML... It should be plain SQL code.
Could you attach the zip file here, so I can inspect it?

**Comment by pleasantgears1** [comment]
[com_storelocator-2.1.1.zip](https://github.com/GreenCape/extension-export/files/1701293/com_storelocator-2.1.1.zip)

**Comment by nibra** [comment]
Thank you, looking at it. The `<tables>` part does not belong to a Joomla manifest file. Getting back to you when I know more.

**Comment by nibra** [comment]
The zip file you sent installs without problems on Joomla 3.8.5. The markers and the general category are set as defined in the SQL file.

What exact did you do to produce the error message?

**Comment by pleasantgears1** [comment]
The zip file was successfully installed but when I go into the component pages in the backend. I see these errors: 1146 Table 'www_mysite_com.#_storelocator_cats' doesn't exist,
0 Table 'www,mysite_com.#__storelocator_marker_types' doesn't exist
There are couple more of similar errors. These tables were not created in the database.

**Comment by nibra** [comment]
Where does the 'www_mysite_com' / 'www,mysite_com' come from? Syntactically, the first one would be a database name, the second makes no sense, though. Joomla does not prepend the table names with the database name. Also, I can navigate to all backend pages of the component (Joomla 3.8.5, PHP 7.0).

**Comment by pleasantgears1** [comment]
It turned out these tables needs to have a prefix just like all other tables inside our Joomla. I was able to ask our programmer to help me correct the names and then execute the script in the sql folder to create these tables. So the # sign should be replaced by database prefix.

prefix_storelocator_cats
prefix_storelocator_marker_types
etc...

May be at your end, database prefixes are not required for your tables.

**Comment by nibra** [comment]
That's something, Joomla's database layer does automatically. I suspect that you might have installed something else that prevents the correct replacements (and adds those  'www_mysite_com' / 'www,mysite_com' prefixes).
